org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Mod
mod_id=moregolems
mod_name=More Golems
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.moregolems
mod_authors=david
mod_description=Fuegt neue Golems hinzu - der erste ist der Wollgolem, der Schafe im Umkreis seiner Truhe schert.

# Minecraft / NeoForge
minecraft_version=26.2
minecraft_version_range=[26.2, 26.3)
neo_version=26.2.0.66
neo_version_range=[26.2.0.0,)
loader_version_range=[11,)
